// <auto-generated />
namespace WattApp.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class t1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t1));
        
        string IMigrationMetadata.Id
        {
            get { return "201407120425253_t1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
